/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tarefas;

import static Tarefas.Home.getUsuarioLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author yuri
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadastro = new javax.swing.JButton();
        btTarefas = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        inputNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        checkNormal = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        checkAdministrador = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btCancelarCadastroTarefa = new javax.swing.JButton();
        btCadastroTarefa = new javax.swing.JButton();
        inputLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputSenhaConfirmacao = new javax.swing.JPasswordField();
        inputSenha = new javax.swing.JPasswordField();

        btCadastro.setText("Cadastro Tarefa");
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });

        btTarefas.setText("Tarefas");
        btTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTarefasActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputNome.setToolTipText("inputTitulo");
        inputNome.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                inputNomeComponentAdded(evt);
            }
        });
        inputNome.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inputNomeInputMethodTextChanged(evt);
            }
        });
        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        buttonGroup1.add(checkNormal);
        checkNormal.setText("Normal");
        checkNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNormalActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de Usuário");

        buttonGroup1.add(checkAdministrador);
        checkAdministrador.setText("Administrador");
        checkAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAdministradorActionPerformed(evt);
            }
        });

        jLabel2.setText("Senha");

        jLabel3.setText("Confirmação de Senha");

        btCancelarCadastroTarefa.setText("Cancelar");
        btCancelarCadastroTarefa.setToolTipText("btCancelar");
        btCancelarCadastroTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarCadastroTarefaActionPerformed(evt);
            }
        });

        btCadastroTarefa.setText("Cadastrar");
        btCadastroTarefa.setToolTipText("btCadastrar");
        btCadastroTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroTarefaActionPerformed(evt);
            }
        });

        inputLogin.setToolTipText("inputTitulo");
        inputLogin.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                inputLoginComponentAdded(evt);
            }
        });
        inputLogin.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inputLoginInputMethodTextChanged(evt);
            }
        });
        inputLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLoginActionPerformed(evt);
            }
        });

        jLabel5.setText("E-mail");

        inputSenhaConfirmacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSenhaConfirmacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(385, 385, 385))
                                .addComponent(inputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(222, 222, 222)
                                        .addComponent(btCancelarCadastroTarefa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btCadastroTarefa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkNormal)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkAdministrador))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(12, 12, 12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputSenhaConfirmacao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(379, 379, 379))
                                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkNormal)
                    .addComponent(checkAdministrador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSenhaConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastroTarefa)
                    .addComponent(btCancelarCadastroTarefa))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static Usuario usuario;
    
    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        new CadastroTarefa().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btCadastroActionPerformed

    private void btTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTarefasActionPerformed
        new ListaTarefas().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btTarefasActionPerformed

    private void inputNomeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_inputNomeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeComponentAdded

    private void inputNomeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputNomeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeInputMethodTextChanged

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeActionPerformed

    private void checkNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkNormalActionPerformed

    private void checkAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAdministradorActionPerformed

    private void btCancelarCadastroTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarCadastroTarefaActionPerformed
        new Home().setVisible(true);
        setVisible(false);
        Home.getUsuarioLogin();
    }//GEN-LAST:event_btCancelarCadastroTarefaActionPerformed

    private void btCadastroTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroTarefaActionPerformed
        String Nome = inputNome.getText();
        String Senha = inputSenha.getText();        
        String ConfirmacaoSenha = inputSenhaConfirmacao.getText();
        String tipoUsuario = "";
        String Login = inputLogin.getText();

        if(checkAdministrador.isSelected()){
            tipoUsuario = "Administrador";
        } else if(checkNormal.isSelected()){
            tipoUsuario = "Normal";
        }
        

        if(Senha.equals(ConfirmacaoSenha)){
            int ID = Usuario.getListaUsuarios().size();

            Usuario newUsuario = new Usuario(ID, Nome, Login, tipoUsuario, Senha, true);
            
            Usuario.setUsuarioLista(newUsuario);

            JOptionPane.showMessageDialog(null, "Usuário cadastrado(a)!");
            
            if(JOptionPane.YES_OPTION == 0){
                new Login().setVisible(true);
                setVisible(false);
            }
            
            }else {
                btCadastro.setVisible(false);
                JOptionPane.showMessageDialog(null, "Senhas diferentes!");
            }
    }//GEN-LAST:event_btCadastroTarefaActionPerformed

    private void inputLoginComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_inputLoginComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLoginComponentAdded

    private void inputLoginInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputLoginInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLoginInputMethodTextChanged

    private void inputLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLoginActionPerformed

    private void inputSenhaConfirmacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSenhaConfirmacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSenhaConfirmacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastro;
    public javax.swing.JButton btCadastroTarefa;
    private javax.swing.JButton btCancelarCadastroTarefa;
    private javax.swing.JButton btTarefas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton checkAdministrador;
    private javax.swing.JRadioButton checkNormal;
    public javax.swing.JTextField inputLogin;
    public javax.swing.JTextField inputNome;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JPasswordField inputSenhaConfirmacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
