/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tarefas;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yuri
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        menuCadastroTarefa = new javax.swing.JButton();
        menuTarefas = new javax.swing.JButton();
        menuCadastroUsuario = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        barraTotalConcluidas = new javax.swing.JProgressBar();
        labelTarefas = new javax.swing.JLabel();
        labelConcluidas = new javax.swing.JLabel();
        totalConcluidasNumero = new javax.swing.JLabel();
        totalPendentesNumero = new javax.swing.JLabel();
        barraTotalPendentes = new javax.swing.JProgressBar();
        labelPendentes = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        totalUsuariosNumero = new javax.swing.JLabel();
        labelUsuarios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaListaTarefas = new javax.swing.JTable();
        nomeUsuario = new javax.swing.JLabel();
        totalTaredasNumero = new javax.swing.JLabel();
        barraTotalTarefas = new javax.swing.JProgressBar();
        labelTotal = new javax.swing.JLabel();
        barraTotalUsuarios = new javax.swing.JProgressBar();
        menuListaUsuarios = new javax.swing.JButton();
        menuPerfil = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("aakar", 1, 18)); // NOI18N
        setMinimumSize(new java.awt.Dimension(500, 300));

        menuCadastroTarefa.setText("Cadastro Tarefa");
        menuCadastroTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroTarefaActionPerformed(evt);
            }
        });

        menuTarefas.setText("Tarefas");
        menuTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTarefasActionPerformed(evt);
            }
        });

        menuCadastroUsuario.setText("Cadastro Usuário");
        menuCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroUsuarioActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        barraTotalConcluidas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                barraTotalConcluidasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        labelTarefas.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        labelTarefas.setText("Tarefas");

        labelConcluidas.setText("Concluídas");

        totalConcluidasNumero.setText("1");

        totalPendentesNumero.setText("2");

        barraTotalPendentes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                barraTotalPendentesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        labelPendentes.setText("Pendentes");

        separador2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        totalUsuariosNumero.setText("Total Usuários");

        labelUsuarios.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        labelUsuarios.setText("Usuários");

        tabelaListaTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaListaTarefas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaListaTarefasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tabelaListaTarefas);

        nomeUsuario.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        nomeUsuario.setText("nome");

        totalTaredasNumero.setText("2");

        barraTotalTarefas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                barraTotalTarefasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        labelTotal.setText("Total");

        barraTotalUsuarios.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                barraTotalUsuariosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        menuListaUsuarios.setText("Usuários");
        menuListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaUsuariosActionPerformed(evt);
            }
        });

        menuPerfil.setText("Perfil");
        menuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPerfilActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel7.setText("Minhas Tarefas");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel8.setText("Olá,");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(11, 11, 11)
                                .addComponent(nomeUsuario))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTarefas)
                                    .addComponent(labelConcluidas)
                                    .addComponent(barraTotalConcluidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPendentes)
                                    .addComponent(barraTotalPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTotal)
                                    .addComponent(barraTotalTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalConcluidasNumero)
                                    .addComponent(totalPendentesNumero)
                                    .addComponent(totalTaredasNumero))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelUsuarios)
                                            .addComponent(barraTotalUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(4, 4, 4)
                                .addComponent(totalUsuariosNumero))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(menuPerfil)
                                .addGap(8, 8, 8)
                                .addComponent(menuCadastroTarefa)
                                .addGap(4, 4, 4)
                                .addComponent(menuCadastroUsuario)))
                        .addGap(6, 6, 6)
                        .addComponent(menuTarefas)
                        .addGap(10, 10, 10)
                        .addComponent(menuListaUsuarios)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuPerfil)
                    .addComponent(menuCadastroTarefa)
                    .addComponent(menuCadastroUsuario)
                    .addComponent(menuTarefas)
                    .addComponent(menuListaUsuarios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(nomeUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTarefas)
                        .addGap(8, 8, 8)
                        .addComponent(labelConcluidas)
                        .addGap(12, 12, 12)
                        .addComponent(barraTotalConcluidas, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelPendentes)
                        .addGap(12, 12, 12)
                        .addComponent(barraTotalPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelTotal)
                        .addGap(12, 12, 12)
                        .addComponent(barraTotalTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(totalConcluidasNumero)
                        .addGap(42, 42, 42)
                        .addComponent(totalPendentesNumero)
                        .addGap(42, 42, 42)
                        .addComponent(totalTaredasNumero))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUsuarios)
                        .addGap(8, 8, 8)
                        .addComponent(barraTotalUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(totalUsuariosNumero)))
                .addGap(8, 8, 8)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btSair)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    List<Tarefa> listaTarefas;
    DefaultTableModel modeloTabela = new DefaultTableModel();
    
    
    public static void getUsuarioLogin (){
        if(Usuario.getTipoUsuario().equals("Normal")){
            menuCadastroTarefa.setVisible(false);
            menuCadastroUsuario.setVisible(false);
            menuTarefas.setVisible(false);
            barraTotalConcluidas.setVisible(false);
            totalConcluidasNumero.setVisible(false);
            barraTotalPendentes.setVisible(false);
            totalPendentesNumero.setVisible(false);
            barraTotalTarefas.setVisible(false);
            totalTaredasNumero.setVisible(false);
            barraTotalUsuarios.setVisible(false);
            totalUsuariosNumero.setVisible(false);
            labelConcluidas.setVisible(false);
            labelPendentes.setVisible(false);
            labelTotal.setVisible(false);
            labelUsuarios.setVisible(false);
            labelTarefas.setVisible(false);
            separador1.setVisible(false);
            separador2.setVisible(false);
            menuListaUsuarios.setVisible(false);
        }
        
        barraTotalConcluidas.setValue(Tarefa.getTotalTarefas()[0]);    
        totalConcluidasNumero.setText(Integer.toString(Tarefa.getTotalTarefas()[0]));
        
        barraTotalPendentes.setValue(Tarefa.getTotalTarefas()[1]);
        totalPendentesNumero.setText(Integer.toString(Tarefa.getTotalTarefas()[1]));
        
        barraTotalTarefas.setValue(Tarefa.getTotalTarefas()[2]);
        totalTaredasNumero.setText(Integer.toString(Tarefa.getTotalTarefas()[2]));
        
        barraTotalUsuarios.setValue(Usuario.getListaUsuarios().size());
        totalUsuariosNumero.setText(Integer.toString(Usuario.getListaUsuarios().size()));
        
        nomeUsuario.setText(Usuario.getNomeUsuario(Usuario.getLoginUsuarioId()));
    }
    
    private void menuCadastroTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroTarefaActionPerformed
        new CadastroTarefa().setVisible(true);
        CadastroTarefa.setListaUsuarios();
        setVisible(false);
    }//GEN-LAST:event_menuCadastroTarefaActionPerformed

    private void menuTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTarefasActionPerformed
        new ListaTarefas().setVisible(true);
        ListaTarefas.getUsuarioLogin();
        
        setVisible(false);
    }//GEN-LAST:event_menuTarefasActionPerformed

    private void menuCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroUsuarioActionPerformed
        new CadastroUsuario().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_menuCadastroUsuarioActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        new Login().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btSairActionPerformed

    private void barraTotalConcluidasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_barraTotalConcluidasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_barraTotalConcluidasAncestorAdded

    private void barraTotalPendentesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_barraTotalPendentesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_barraTotalPendentesAncestorAdded

    private void barraTotalTarefasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_barraTotalTarefasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_barraTotalTarefasAncestorAdded

    private void barraTotalUsuariosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_barraTotalUsuariosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_barraTotalUsuariosAncestorAdded

    private void tabelaListaTarefasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaListaTarefasAncestorAdded
  
        listaTarefas = Tarefa.getTarefaUsuarioEspecifico(Usuario.getLoginUsuarioId());
        
        modeloTabela.addColumn("ID");
        modeloTabela.addColumn("Título");
        modeloTabela.addColumn("Descrição");    
        modeloTabela.addColumn("Data de Entrega");
        modeloTabela.addColumn("Prioridade");      
        modeloTabela.addColumn("Responsável");    
        modeloTabela.addColumn("Status");

        int i = 0;

        for (Tarefa tarefa : listaTarefas) {
            modeloTabela.addRow(new Object[]{
                Tarefa.getIdTarefa(i), 
                Tarefa.getTitleTarefa(i, listaTarefas), 
                Tarefa.getDescricaoTarefa(i, listaTarefas), 
                Tarefa.getDataEntregaTarefa(i, listaTarefas), 
                Tarefa.getPrioridadeTarefa(i, listaTarefas), 
                Tarefa.getUsuarioResponsavel(Tarefa.getIdUsuarioResponsavel(i, listaTarefas)),
                Tarefa.getStatusTarefa(i, listaTarefas),
            });      

            i = i + 1;
        }

        tabelaListaTarefas.setModel(modeloTabela);
    }//GEN-LAST:event_tabelaListaTarefasAncestorAdded

    private void menuListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaUsuariosActionPerformed
        new ListaUsuarios().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_menuListaUsuariosActionPerformed

    private void menuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPerfilActionPerformed
        new Perfil().setVisible(true);
        Perfil.setInfoUsuario();
        setVisible(false);
    }//GEN-LAST:event_menuPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
                
            }
        });
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JProgressBar barraTotalConcluidas;
    private static javax.swing.JProgressBar barraTotalPendentes;
    private static javax.swing.JProgressBar barraTotalTarefas;
    private static javax.swing.JProgressBar barraTotalUsuarios;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private static javax.swing.JLabel labelConcluidas;
    private static javax.swing.JLabel labelPendentes;
    private static javax.swing.JLabel labelTarefas;
    private static javax.swing.JLabel labelTotal;
    private static javax.swing.JLabel labelUsuarios;
    private static javax.swing.JButton menuCadastroTarefa;
    private static javax.swing.JButton menuCadastroUsuario;
    private static javax.swing.JButton menuListaUsuarios;
    private javax.swing.JButton menuPerfil;
    private static javax.swing.JButton menuTarefas;
    private static javax.swing.JLabel nomeUsuario;
    private static javax.swing.JSeparator separador1;
    private static javax.swing.JSeparator separador2;
    private javax.swing.JTable tabelaListaTarefas;
    private static javax.swing.JLabel totalConcluidasNumero;
    private static javax.swing.JLabel totalPendentesNumero;
    private static javax.swing.JLabel totalTaredasNumero;
    private static javax.swing.JLabel totalUsuariosNumero;
    // End of variables declaration//GEN-END:variables
}
